# Dockerfile
FROM node:18-alpine

# Establecer directorio de trabajo
WORKDIR /api-libros

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]