### Obtener todos los libros
GET http://localhost:3000/api/libros

### Obtener un libro específico
GET http://localhost:3000/api/libros/1

### Crear un nuevo libro
POST http://localhost:3000/api/libros
Content-Type: application/json
{
  "titulo": "Cien años de soledad",
  "autor": "García Márquez",
  "año": 1967,
  "precio": 45.99
}

### Crear un nuevo libro
POST http://localhost:3000/api/libros
Content-Type: application/json
{
  "titulo": "La vida",
  "autor": "García",
  "año": 1967,
  "precio": 45.99
}

### Crear un nuevo libro
POST http://localhost:3000/api/libros
Content-Type: application/json

{
  "titulo": "El Quijote",
  "autor": "Miguel de Cervantes",
  "año": 1055,
  "precio": 15.96
}

### Crear un nuevo libro
POST http://localhost:3000/api/libros
Content-Type: application/json
{
  "titulo": "Don Juan",
  "autor": "Lord Byron",
  "año": 1819,
  "precio": 25.99
}
### Actualizar un libro
PUT http://localhost:3000/api/libros/6970b01ce12d7f07fcb7f38b
Content-Type: application/json

{
  "titulo": "El Quijote Actualizado",
  "autor": "Cervantes",
  "año": 1605
}

### Eliminar un libro
DELETE http://localhost:3000/api/libros/6970b01ce12d7f07fcb7f38b

### Con parámetros de consulta
GET http://localhost:3000/api/libros?autor=Cervantes&año=1605

### Con headers personalizado
GET http://localhost:3000/api/libros
Authorization: Bearer token123456
X-Custom-Header: valor-personalizado